// <auto-generated />
namespace Tahri_Company.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11Catalog : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11Catalog));
        
        string IMigrationMetadata.Id
        {
            get { return "201612260044506_11Catalog"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
